blank_issues_enabled: false
contact_links:
  - name: Ephemeral Community Support (Discord)
    url: https://discord.gg/XMsJqZJJeT
    about: Please ask Ephemeral related questions in the support channel.
